version: '3.13'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      uvicorn TestAuthApp.asgi:application
      --host 0.0.0.0
      --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file:
      - .env
