# Generated by Django 5.1.3 on 2024-11-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyauthuser',
            name='is_mobile_app_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyauthuser',
            name='mobile_app_token',
            field=models.TextField(default=None, null=True, verbose_name='mobile_app_token'),
        ),
        migrations.AlterField(
            model_name='storyauthuser',
            name='story',
            field=models.TextField(default=None, null=True, verbose_name='story'),
        ),
    ]
