# Generated by Django 5.1.3 on 2024-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_storyauthuser_is_mobile_app_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyauthuser',
            name='is_mobile_app_verified',
        ),
        migrations.AddField(
            model_name='storyauthuser',
            name='mobile_identifier',
            field=models.TextField(default=None, null=True, verbose_name='mobile_identifier'),
        ),
    ]
