# Generated by Django 5.1.3 on 2024-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_storyauthuser_is_mobile_app_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftauthuser',
            name='jwt_token',
            field=models.TextField(default='', max_length=255, verbose_name='jwt_token'),
        ),
        migrations.AddField(
            model_name='storyauthuser',
            name='jwt_token',
            field=models.TextField(default='', max_length=255, verbose_name='jwt_token'),
        ),
    ]
