# Generated by Django 5.1.3 on 2024-11-16 14:04

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_nftauthuser_jwt_token_storyauthuser_jwt_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyauthuser',
            name='story',
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(max_length=2000, verbose_name='story')),
                ('correct_options', models.TextField(max_length=1000, verbose_name='correct_options')),
                ('incorrect_options', models.TextField(max_length=1000, verbose_name='incorrect_options')),
                ('expires_at', models.DateTimeField(default=base.models.expriration_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
